# Generated by Django 5.2.15 on 2026-09-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_materia_conteudo_progressoleitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('alt_a', models.TextField()),
                ('alt_b', models.TextField()),
                ('alt_c', models.TextField()),
                ('alt_d', models.TextField()),
                ('alt_e', models.TextField()),
                ('resposta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='app.conteudo')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['pk'],
            },
        ),
    ]
